env:
  global:
    secure: U951ERKryL4D+rmJCDEAKREQZ54zQA6HU4RQpQ4L78r5juK2fC+wSVYBTyb3hdTjQ+xTQ4t61MbR0OI+un5RXI3zDYeuOJLIsB29f8bh7D3TEv4Y+fGQTS9hXPLko+LixdFfC8Xil9X1XI5BrWQqagNXdt0c08vcmoZ1Y1IalSk94hG1dVjrHktYHav/wD8LG+oTfbcDWXf8EROkmP3e5m2jb9gbXD4a4IQv246edmfyefiz9G1Iwtgv5imcNun5MDsf/fslpENdUaRautz8RF6wgujW5WTFMxVgyt32ijWxXpd3KkRXqzv1MDGYTyxX4iGMsuWb08+HPUnrbJjlFECQy2Hqq00BiuNtmlM+Q9iBkt6tecjkZuAOpkRUinab8Wk6wz5EtaR4aCVE7F7UJkqq480aelsLUfrdxwqhbMA+VmKvjyoKOByU1bS5Z3LR1tPpT+NsXNNycUnB3lH4xGoH6tidmIJg+W24wTsLszCJwydU+XxiCDQaQOJOEQXT2vzZtrzdP7kN2490LP7D7/lKDcrz1N/9MNugLuCGdPDsaS5oedjtbWfjwjhX6/tvDNAaDw8LCKI3r+IBWsEC8HcgJc5Nw+uBx059PP4ZgJSwfGqgpT8SqHx6aKKnmq8VemQwsCQtfBhf4eySCobi4WjM/pj541YuHr4XcthtaTE=
dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules

before_script:
  - npm install -g @angular/cli
  
install:
  - npm install

script:
  - npm build --prod

deploy:
  provider: s3
  bucket: "vehicle-app"
  skip_cleanup: true
  acl: public_read
  region: us-east-2
  local_dir: dist
